# Generated by Django 6.1.1 on 2026-09-13 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_corpmember_email_alter_corpmember_lga_posted_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='corpmember',
            managers=[
            ],
        ),
    ]
