# Generated by Django 6.1.1 on 2026-09-12 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Education', 'Education & Teaching'), ('Healthcare', 'Healthcare & Medicine'), ('Public Sector', 'Government & Public Sector'), ('Private Sector', 'Private Corporate & Tech'), ('NGO', 'NGOs & Non-Profits'), ('Legal', 'Legal & Law Firms')], default='Education', max_length=50)),
                ('address', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('stipend', models.PositiveIntegerField(blank=True, help_text='Monthly stipend in NGN', null=True)),
                ('provides_accommodation', models.BooleanField(default=False)),
                ('accepting_corpers', models.BooleanField(default=True)),
                ('working_days', models.CharField(default='Mon - Fri', max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppas', to='locations.lga')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppas', to='locations.state')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ppa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ppas.ppa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppa_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('ppa', 'user')},
            },
        ),
    ]
