# Generated by Django 6.1.1 on 2026-09-14 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('ppas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ppa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.RenameField(
            model_name='ppa',
            old_name='contact_email',
            new_name='email',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='ppa',
            name='accepting_corpers',
        ),
        migrations.RemoveField(
            model_name='ppa',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='ppa',
            name='provides_accommodation',
        ),
        migrations.RemoveField(
            model_name='ppa',
            name='working_days',
        ),
        migrations.AddField(
            model_name='ppa',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='Direct link to Google Maps location', max_length=500),
        ),
        migrations.AddField(
            model_name='ppa',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ppa',
            name='verified',
            field=models.BooleanField(default=False, help_text='Designates whether this PPA is officially verified.'),
        ),
        migrations.AlterField(
            model_name='ppa',
            name='category',
            field=models.CharField(choices=[('Education', 'Education'), ('Healthcare', 'Healthcare'), ('Agriculture', 'Agriculture'), ('Public Sector', 'Public Sector'), ('Private Sector', 'Private Sector'), ('NGO', 'NGO')], default='Public Sector', max_length=50),
        ),
        migrations.AlterField(
            model_name='ppa',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ppa',
            name='latitude',
            field=models.FloatField(blank=True, help_text='GPS Latitude', null=True),
        ),
        migrations.AlterField(
            model_name='ppa',
            name='lga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.lga'),
        ),
        migrations.AlterField(
            model_name='ppa',
            name='longitude',
            field=models.FloatField(blank=True, help_text='GPS Longitude', null=True),
        ),
        migrations.AlterField(
            model_name='ppa',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ppa',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.state'),
        ),
        migrations.AlterField(
            model_name='ppa',
            name='stipend',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ppa',
            index=models.Index(fields=['state', 'lga'], name='ppas_ppa_state_i_149bea_idx'),
        ),
        migrations.AddIndex(
            model_name='ppa',
            index=models.Index(fields=['name'], name='ppas_ppa_name_4fc7f1_idx'),
        ),
    ]
