# Generated by Django 6.1.1 on 2026-09-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppas', '0002_alter_ppa_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppa',
            name='stipend',
        ),
        migrations.AlterField(
            model_name='ppa',
            name='category',
            field=models.CharField(choices=[('Education', 'Education'), ('Public Sector', 'Public Sector'), ('Private Sector', 'Private Sector'), ('NGO', 'NGO'), ('Healthcare', 'Healthcare')], default='Public Sector', max_length=50),
        ),
        migrations.AlterField(
            model_name='ppa',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='ppa',
            name='google_maps_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ppa',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ppa',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ppa',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ppa',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
